### ISSUE TITLE
unified version of iris? / 8 Nov 2022

### ISSUE THREAD

**Issue by vetter** [ORNL/iris#10]
Is everyone using the same version of iris? 
I was not sure yesterday about the different versions of iris that we are discussing.
can we clarify before Wednesday? Thanks, 

cc: @BeauJoh @miniskar @Geekdude @seyonglee

**Comment by miniskar** [comment]
We have one unified internal version of IRIS. It includes all extensions of IRIS so far. We will soon merge it also with ornlmain branch.

**Comment by vetter** [comment]
thanks. what is the URL for the other version? Thanks,

**Comment by miniskar** [comment]
Here is the link: https://code.ornl.gov/brisbane/iris/-/tree/memsysv2.json
Branch name: memsysv2.json

**Comment by vetter** [comment]
thanks for the update today. i'm moving this into the internal dev repo.
