### ISSUE TITLE
More complex application examples

### ISSUE THREAD

**Issue by milthorpe** [ORNL/iris#11]
The application examples currently in https://github.com/ORNL/iris/tree/main/apps are not complex enough to fully demonstrate the capabilities of IRIS.

In particular, it would be good to have some examples with non-trivial task graphs e.g. multiple layers of tasks (of varying depths), multiple input/output dependencies for a single task; combinations of data and task dependencies.

**Comment by vetter** [comment]
i'm moving this to the internal dev repo.
