### ISSUE TITLE
IRIS presentation at SIAM PP

### ISSUE THREAD

**Issue by vetter** [ORNL/iris#4]
we need a speaker for the SIAM PP talk on IRIS.

**Comment by BeauJoh** [comment]
I can give this talk, I don't suppose Jungwon had a slidedeck ready to go?

**Comment by vetter** [comment]
@seyonglee @BeauJoh : thanks for volunteering. i haven't looked into timezones so you might want to check that before one of your commit :)

I have a lot of IRIS slides so it should not be too much effort to curate a PPTX pres.

let me know what you two decide.

Thanks,

**Comment by vetter** [comment]
@pedrovalerolara : can you tell @seyonglee and @BeauJoh about the siam pp pres? Thanks,

**Comment by seyonglee** [comment]
@BeauJoh Then, I assume that you will present this at the SIAM PP.

**Comment by seyonglee** [comment]
@BeauJoh OK; I will present IRIS at SIAM PP. (Good luck with your game!)
